version: '3.9'
services:
 redis:
  image: redis:latest
  container_name: redis_container
  ports:
   - "6379:${REDIS_PORT}"
  volumes:
   - ./redisdata:/data
 app:
  image: my-fastapi-app:latest
  ports:
   - "8000:8000"
  depends_on:
   - redis
  environment:
   DATABASE_URL: ${DATABASE_URL}
   REDIS_HOST: ${REDIS_HOST}
   REDIS_PORT: ${REDIS_PORT}
   JWT_SECRET_KEY: ${JWT_SECRET_KEY}
   JWT_ALGORITHM: ${JWT_ALGORITHM}
  volumes:
   - ./data:/app/data